/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Context } from "caracal_polaris/dist/types/model/context.model";
export namespace Components {
    interface ApxButton {
        "caption": string;
        "ctx": Context;
        "isDefault": boolean;
        "next": string;
    }
    interface ApxCheckbox {
        "caption": string;
        "ctx": Context;
        "name": string;
        "value": boolean;
    }
    interface ApxGrid {
        "caption": string;
        "ctx": Context;
        "headers": any;
        "value": Array<any>;
    }
    interface ApxInput {
        "caption": string;
        "ctx": Context;
        "name": string;
        "type": string;
        "value": string;
    }
    interface ApxLoader {
        "ctx": Context;
    }
    interface ApxMain {
        "activity": string;
        "ctx": Context;
        "process": string;
        "sessionId": string;
    }
    interface ApxMenu {
        "ctx": Context;
        "items": any;
    }
    interface ResizeHandle {
    }
}
declare global {
    interface HTMLApxButtonElement extends Components.ApxButton, HTMLStencilElement {
    }
    var HTMLApxButtonElement: {
        prototype: HTMLApxButtonElement;
        new (): HTMLApxButtonElement;
    };
    interface HTMLApxCheckboxElement extends Components.ApxCheckbox, HTMLStencilElement {
    }
    var HTMLApxCheckboxElement: {
        prototype: HTMLApxCheckboxElement;
        new (): HTMLApxCheckboxElement;
    };
    interface HTMLApxGridElement extends Components.ApxGrid, HTMLStencilElement {
    }
    var HTMLApxGridElement: {
        prototype: HTMLApxGridElement;
        new (): HTMLApxGridElement;
    };
    interface HTMLApxInputElement extends Components.ApxInput, HTMLStencilElement {
    }
    var HTMLApxInputElement: {
        prototype: HTMLApxInputElement;
        new (): HTMLApxInputElement;
    };
    interface HTMLApxLoaderElement extends Components.ApxLoader, HTMLStencilElement {
    }
    var HTMLApxLoaderElement: {
        prototype: HTMLApxLoaderElement;
        new (): HTMLApxLoaderElement;
    };
    interface HTMLApxMainElement extends Components.ApxMain, HTMLStencilElement {
    }
    var HTMLApxMainElement: {
        prototype: HTMLApxMainElement;
        new (): HTMLApxMainElement;
    };
    interface HTMLApxMenuElement extends Components.ApxMenu, HTMLStencilElement {
    }
    var HTMLApxMenuElement: {
        prototype: HTMLApxMenuElement;
        new (): HTMLApxMenuElement;
    };
    interface HTMLResizeHandleElement extends Components.ResizeHandle, HTMLStencilElement {
    }
    var HTMLResizeHandleElement: {
        prototype: HTMLResizeHandleElement;
        new (): HTMLResizeHandleElement;
    };
    interface HTMLElementTagNameMap {
        "apx-button": HTMLApxButtonElement;
        "apx-checkbox": HTMLApxCheckboxElement;
        "apx-grid": HTMLApxGridElement;
        "apx-input": HTMLApxInputElement;
        "apx-loader": HTMLApxLoaderElement;
        "apx-main": HTMLApxMainElement;
        "apx-menu": HTMLApxMenuElement;
        "resize-handle": HTMLResizeHandleElement;
    }
}
declare namespace LocalJSX {
    interface ApxButton {
        "caption"?: string;
        "ctx"?: Context;
        "isDefault"?: boolean;
        "next"?: string;
    }
    interface ApxCheckbox {
        "caption"?: string;
        "ctx"?: Context;
        "name"?: string;
        "onCheckChanged"?: (event: CustomEvent<boolean>) => void;
        "value"?: boolean;
    }
    interface ApxGrid {
        "caption"?: string;
        "ctx"?: Context;
        "headers"?: any;
        "value"?: Array<any>;
    }
    interface ApxInput {
        "caption"?: string;
        "ctx"?: Context;
        "name"?: string;
        "type"?: string;
        "value"?: string;
    }
    interface ApxLoader {
        "ctx"?: Context;
    }
    interface ApxMain {
        "activity"?: string;
        "ctx"?: Context;
        "process"?: string;
        "sessionId"?: string;
    }
    interface ApxMenu {
        "ctx"?: Context;
        "items"?: any;
    }
    interface ResizeHandle {
    }
    interface IntrinsicElements {
        "apx-button": ApxButton;
        "apx-checkbox": ApxCheckbox;
        "apx-grid": ApxGrid;
        "apx-input": ApxInput;
        "apx-loader": ApxLoader;
        "apx-main": ApxMain;
        "apx-menu": ApxMenu;
        "resize-handle": ResizeHandle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "apx-button": LocalJSX.ApxButton & JSXBase.HTMLAttributes<HTMLApxButtonElement>;
            "apx-checkbox": LocalJSX.ApxCheckbox & JSXBase.HTMLAttributes<HTMLApxCheckboxElement>;
            "apx-grid": LocalJSX.ApxGrid & JSXBase.HTMLAttributes<HTMLApxGridElement>;
            "apx-input": LocalJSX.ApxInput & JSXBase.HTMLAttributes<HTMLApxInputElement>;
            "apx-loader": LocalJSX.ApxLoader & JSXBase.HTMLAttributes<HTMLApxLoaderElement>;
            "apx-main": LocalJSX.ApxMain & JSXBase.HTMLAttributes<HTMLApxMainElement>;
            "apx-menu": LocalJSX.ApxMenu & JSXBase.HTMLAttributes<HTMLApxMenuElement>;
            "resize-handle": LocalJSX.ResizeHandle & JSXBase.HTMLAttributes<HTMLResizeHandleElement>;
        }
    }
}
