/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Context } from "caracal_polaris/dist/types/model/context.model";
export namespace Components {
    interface DcxDashboard {
        "ctx": Context;
        "type": string;
        "value": any;
    }
    interface DcxLoader {
        "ctx": Context;
    }
    interface DcxMain {
        "activity": string;
        "ctx": Context;
        "process": string;
        "sessionId": string;
    }
    interface DcxMenu {
        "ctx": Context;
        "items": any;
    }
}
declare global {
    interface HTMLDcxDashboardElement extends Components.DcxDashboard, HTMLStencilElement {
    }
    var HTMLDcxDashboardElement: {
        prototype: HTMLDcxDashboardElement;
        new (): HTMLDcxDashboardElement;
    };
    interface HTMLDcxLoaderElement extends Components.DcxLoader, HTMLStencilElement {
    }
    var HTMLDcxLoaderElement: {
        prototype: HTMLDcxLoaderElement;
        new (): HTMLDcxLoaderElement;
    };
    interface HTMLDcxMainElement extends Components.DcxMain, HTMLStencilElement {
    }
    var HTMLDcxMainElement: {
        prototype: HTMLDcxMainElement;
        new (): HTMLDcxMainElement;
    };
    interface HTMLDcxMenuElement extends Components.DcxMenu, HTMLStencilElement {
    }
    var HTMLDcxMenuElement: {
        prototype: HTMLDcxMenuElement;
        new (): HTMLDcxMenuElement;
    };
    interface HTMLElementTagNameMap {
        "dcx-dashboard": HTMLDcxDashboardElement;
        "dcx-loader": HTMLDcxLoaderElement;
        "dcx-main": HTMLDcxMainElement;
        "dcx-menu": HTMLDcxMenuElement;
    }
}
declare namespace LocalJSX {
    interface DcxDashboard {
        "ctx"?: Context;
        "type"?: string;
        "value"?: any;
    }
    interface DcxLoader {
        "ctx"?: Context;
    }
    interface DcxMain {
        "activity"?: string;
        "ctx"?: Context;
        "process"?: string;
        "sessionId"?: string;
    }
    interface DcxMenu {
        "ctx"?: Context;
        "items"?: any;
    }
    interface IntrinsicElements {
        "dcx-dashboard": DcxDashboard;
        "dcx-loader": DcxLoader;
        "dcx-main": DcxMain;
        "dcx-menu": DcxMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dcx-dashboard": LocalJSX.DcxDashboard & JSXBase.HTMLAttributes<HTMLDcxDashboardElement>;
            "dcx-loader": LocalJSX.DcxLoader & JSXBase.HTMLAttributes<HTMLDcxLoaderElement>;
            "dcx-main": LocalJSX.DcxMain & JSXBase.HTMLAttributes<HTMLDcxMainElement>;
            "dcx-menu": LocalJSX.DcxMenu & JSXBase.HTMLAttributes<HTMLDcxMenuElement>;
        }
    }
}
